#!/usr/bin/env python
"""
Python interface for Cart3D: :file:`pycart`
===========================================

This function provides a master interface for pyCart.  All of the functionality
from this script is also accessible from the :mod:`pyCart` module using
relatively simple commands.

:Usage:
    .. code-block:: bash
    
        $ pycart [options]
    
:Options:

    -h, --help
        Display this help message and quit
        
    -c
        Check status and don't submit new jobs
        
    -q QUEUE
        Submit to a specific queue (defaults to "sls_aero1")

    -n NJOB
        Submit at most *NJOB* PBS scripts (defaults to unlimited)
        
    -f FNAME
        Use pyCart input file *FNAME* (defaults to 'pyCart.json')

:Versions:
    * 2014.10.03 ``@ddalle``: Started
"""

# Import the full module
import pyCart
# Input parsing
from pyCart.argread import readflagstar
    
# Check if run as a script.
if __name__ == "__main__":
    # Parse inputs.
    a, kw = readflagstar(pyCart.os.sys.argv)
    
    # Filter command...
    
    # Check for a help flag.
    if kw.get('h') or kw.get('help'):
        print(__doc__)
        pyCart.os.sys.exit()
        
    # Get file name.
    fname = kw.get('f', 'pyCart.json')
    
    # Try to read it.
    cart3d = pyCart.Cart3d(fname)
    
    # Process inputs.
    if kw.get('c'):
        # Display status.
        cart3d.DisplayStatus(**kw)
    else:
        # Do it.
        cart3d.SubmitJobs(**kw)
