#!/bin/bash
#PBS -S /bin/bash
#PBS -N m0.8a10b0bullet
#PBS -r n
#PBS -j oe
#PBS -l select=1:ncpus=24:mpiprocs=24:model=has
#PBS -l walltime=2:00:00
#PBS -W group_list=e0847
#PBS -q devel

# Go to the working directory.
cd /u/wk/jmeeroff/usr/cape/test/pyfun/02_adiabatic/bullet/m0.80a10.0b0.0

# Set umask.
umask 0027

# Additional shell commands
. $MODULESHOME/init/bash
module load fun3d
module load pycart

# Call the FUN3D interface.
run_fun3d.py
