#!MC 1400
# Created by Tecplot 360 build 14.0.2.35002
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!OPENLAYOUT  "layout.lay"
$!EXPORTSETUP EXPORTFORMAT = PNG
$!EXPORTSETUP EXPORTREGION = ALLFRAMES
$!EXPORTSETUP IMAGEWIDTH = 1024
$!EXPORTSETUP USESUPERSAMPLEANTIALIASING = YES
$!EXPORTSETUP EXPORTFNAME = 'export.png'
$!EXPORT 
  EXPORTREGION = ALLFRAMES
$!Quit
