#!MC 1400
# Created by Tecplot 360 build 14.0.2.35002
$!VarSet |MFBD| = ''
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!OPENLAYOUT  "iso-comp.lay"
$!EXPORTSETUP EXPORTFORMAT = PNG
$!EXPORTSETUP EXPORTREGION = ALLFRAMES
$!EXPORTSETUP IMAGEWIDTH = 850
$!EXPORTSETUP USESUPERSAMPLEANTIALIASING = YES
$!EXPORTSETUP EXPORTFNAME = 'iso-comp.png'
$!EXPORT 
  EXPORTREGION = ALLFRAMES
$!Quit
$!RemoveVar |MFBD|
